[features]
seeds = false
skip-lint = false
[programs.localnet]
transferhook = "7aeu4HRHR4UwQndRDyh5f7nMwgxgH3rrtLgRntxdivZw"

[provider]
cluster = "Localnet"
wallet = "./bash/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test.validator]
ticks_per_slot = 8
slots_per_epoch = "64"
